In [24]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains, ScrollOrigin
import pandas as pd

#### Click Iphone

In [25]:
url = 'https://www.thegioididong.com/dtdd'
driver = webdriver.Chrome()
driver.get(url)

In [26]:
ip_xpath = '//a[@data-href="dtdd-apple-iphone"]'
ip_elm = driver.find_element(by=By.XPATH, value=ip_xpath)

In [27]:
ip_elm.click()

In [28]:
driver.back()

#### Click Iphone, Samsung, Xiaomi

In [29]:
hang_elm = driver.find_element(By.XPATH, '/html/body/div[6]/div[4]/section/div[1]/div/div[3]/div[1]')
hang_elm.click()

In [30]:
samsung_elm = driver.find_element(By.XPATH, '/html/body/div[6]/div[4]/section/div[1]/div/div[3]/div[2]/div[1]/a[1]')
iphone_elm = driver.find_element(By.XPATH, '/html/body/div[6]/div[4]/section/div[1]/div/div[3]/div[2]/div[1]/a[2]')
xiaomi_elm = driver.find_element(By.XPATH, '/html/body/div[6]/div[4]/section/div[1]/div/div[3]/div[2]/div[1]/a[4]')

In [31]:
samsung_elm.click()
iphone_elm.click()
xiaomi_elm.click()

In [32]:
xem_ket_qua_elm = driver.find_element(By.XPATH, '/html/body/div[6]/div[4]/section/div[1]/div/div[3]/div[2]/div[2]/a[2]')
xem_ket_qua_elm.click()

#### Show more:

In [34]:
show_more_elm = driver.find_element(By.XPATH, '//*[@id="categoryPage"]/div[3]/div[2]/a')
show_more_elm.click()

In [35]:
while True:
    try:
        show_more_elm.click()
    except:
        print('we are at the end of the page!')
        break

we are at the end of the page!

#### Get product infomation

In [12]:
# products_elm = driver.find_elements(By.CLASS_NAME, 'item')
# len(products_elm)

In [70]:
listproduct_elm = driver.find_element(By.CLASS_NAME, 'listproduct')
product_list = listproduct_elm.find_elements(By.CLASS_NAME, 'item')
len(product_list)

84

In [71]:
product_list

[<selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2048")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2049")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2050")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2051")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2052")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2053")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2054")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2055")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2056")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2057")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2058")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2059")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2060")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2061")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2062")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2063")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2064")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2065")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2066")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2067")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2068")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2069")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2070")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2071")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2072")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2073")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2074")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2075")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2076")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2077")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2078")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2079")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2080")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2081")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2082")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2083")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2084")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2085")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2086")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2087")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2088")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2089")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2090")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2091")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2092")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2093")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2094")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2095")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2096")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2097")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2098")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2099")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2100")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2101")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2102")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2103")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2104")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2105")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2106")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2107")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2108")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2109")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2110")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2111")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2112")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2113")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2114")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2115")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2116")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2117")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2118")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2119")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2120")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2121")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2122")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2042")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2043")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2044")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2045")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2046")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2038")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2039")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2040")>,
 <selenium.webdriver.remote.webelement.WebElement (session="698f9fc74b3e71f5d51588f979645e97", element="f.4C1E2982436D28D4E25347B15428373B.d.2D951EC86F396849FA8F170BF852E265.e.2041")>]

#### Try get infomation of 1 phone

In [38]:
phone_elm = product_list[0]
phone_elm

In [39]:
# opt1: get phone name:
phone_name = phone_elm.find_element(By.XPATH, './/h3[@title]').text
phone_name

'iPhone 15 Pro Max 256GB'

In [ ]:
# opt2: get phone name:
phone_elm.find_element(By.XPATH, './/h3[@title]').get_attribute('title')

'Điện thoại iPhone 15 Pro Max 256GB'

In [ ]:
# get price:
price = phone_elm.find_element(By.XPATH, value='.//strong[@class="price"]').text
price

'29.590.000₫'

In [ ]:
# opt1: get utility:
utility = phone_elm.find_element(By.CLASS_NAME, 'utility').text
utility

'Chip Apple A17 Pro 6 nhân\nRAM: 8 GB\nDung lượng: 256 GB\nCamera sau: Chính 48 MP & Phụ 12 MP, 12 MP\nCamera trước: 12 MP\nPin 4422 mAh, Sạc 20 W'

In [ ]:
# opt2 to get utility
phone_elm.find_element(By.CLASS_NAME, 'utility').get_attribute('textContent')

'\n            Chip Apple A17 Pro 6 nhân\n            RAM: 8 GB\n            Dung lượng: 256 GB\n            Camera sau: Chính 48 MP & Phụ 12 MP, 12 MP\n            Camera trước: 12 MP\n            Pin 4422 mAh,  Sạc 20 W\n    '

In [ ]:
# get product image:
phone_img_link = phone_elm.find_element(By.XPATH, './/img').get_attribute('src')
phone_img_link

'https://cdn.tgdd.vn/Products/Images/42/305658/iphone-15-pro-max-blue-thumbnew-600x600.jpg'

##### Create get product info function

In [40]:
def get_product_info(product_elm):
    # opt1: get phone name:
    phone_name = product_elm.find_element(By.XPATH, './/h3[@title]').text

    # get price:
    price = product_elm.find_element(By.XPATH, value='.//strong[@class="price"]').text

    # opt1: get utility:
    utility = product_elm.find_element(By.CLASS_NAME, 'utility').text

    # get product image:
    phone_img_link = product_elm.find_element(By.XPATH, './/img').get_attribute('src')

    result = {
        'name': phone_name,
        'price': price,
        'utility': utility,
        'img_link': phone_img_link
    }
    return result

In [41]:
get_product_info(product_elm=product_list[0])

{'name': 'iPhone 15 Pro Max 256GB',
 'price': '29.590.000₫',
 'utility': 'Chip Apple A17 Pro 6 nhân\nRAM: 8 GB\nDung lượng: 256 GB\nCamera sau: Chính 48 MP & Phụ 12 MP, 12 MP\nCamera trước: 12 MP\nPin 4422 mAh, Sạc 20 W',
 'img_link': 'https://cdn.tgdd.vn/Products/Images/42/305658/iphone-15-pro-max-blue-thumbnew-600x600.jpg'}

#### Get all products infomation

In [42]:
all_product_list = []

for prd_elm in product_list:
    product_info = get_product_info(product_elm=prd_elm)
    all_product_list.append(product_info)

In [43]:
df = pd.DataFrame(all_product_list)
df.head()

,name,price,utility,img_link
0,iPhone 15 Pro Max 256GB,29.590.000₫,Chip Apple A17 Pro 6 nhân\nRAM: 8 GB\nDung lượ...,https://cdn.tgdd.vn/Products/Images/42/305658/...
1,iPhone 13 256GB,16.990.000₫,Chip Apple A15 Bionic\nRAM: 4 GB\nDung lượng: ...,https://cdn.tgdd.vn/Products/Images/42/250258/...
2,Samsung Galaxy S23 Ultra 5G 256GB,24.990.000₫,Chip Snapdragon 8 Gen 2 for Galaxy\nRAM: 8 GB\...,https://cdn.tgdd.vn/Products/Images/42/249948/...
3,Xiaomi Redmi Note 13 (8GB/128GB),4.390.000₫,Chip Snapdragon 685 8 nhân\nRAM: 8 GB\nDung lư...,https://cdn.tgdd.vn/Products/Images/42/309831/...
4,Samsung Galaxy A55 5G (8GB/256GB),10.190.000₫,Chip Exynos 1480 8 nhân\nRAM: 8 GB\nDung lượng...,https://cdn.tgdd.vn/Products/Images/42/322670/...

In [44]:
len(df)

84

#### Get Product Description

In [116]:
phone_elm  = product_list[0]

In [117]:
# B1: Click vao product:
phone_elm.click()

In [118]:
driver.current_url

'https://www.thegioididong.com/dtdd/iphone-15-pro-max'

In [119]:
# B2: get production description:
product_description = driver.find_element(By.CLASS_NAME, 'content-article').get_attribute('textContent')
product_description

'\n                    Đặc điểm nổi bật của iPhone 15 Pro Max• Tăng độ cứng cáp và tối ưu khối lượng với chất liệu Titan• Bứt phá mọi giới hạn về hiệu năng nhờ chip A17 Pro• Phiên bản duy nhất cải tiến camera tele 5x• Tích hợp camera 48 MP• Nút tác vụ (Action Button) thay thế cần gạt rung• Chuyển đổi cổng sạc USB-C, truyền tải dữ liệu tốc độ caoLý do chọn mua iPhone 15 Pro Max tại Thế Giới Di ĐộngiPhone 15 Pro Max là một chiếc điện thoại thông minh cao cấp được mong đợi nhất năm 2023. Với nhiều tính năng mới và cải tiến, iPhone 15 Pro Max chắc chắn sẽ là một lựa chọn tuyệt vời cho những người dùng đang tìm kiếm một chiếc điện thoại có hiệu năng mạnh mẽ, camera chất lượng và thiết kế sang trọng.• Sản phẩm chính hãng, đảm bảo chất lượng: Thế Giới Di Động là nhà bán lẻ điện thoại di động lớn nhất Việt Nam, cam kết cung cấp sản phẩm chính hãng, đảm bảo chất lượng. Bạn có thể yên tâm về xuất xứ sản phẩm và có thể tận hưởng trải nghiệm sử dụng tốt nhất.• Ưu đãi và khuyến mãi hấp dẫn: Thế Giới Di Động thường xuyên có các chương trình khuyến mãi, giảm giá và tặng quà kèm, giúp bạn tiết kiệm được một khoản tiền khi mua iPhone 15 Pro Max.• Hệ thống cửa hàng rộng khắp: Thế Giới Di Động có mạng lưới cửa hàng rộng khắp trên toàn quốc, giúp bạn dễ dàng tìm được một cửa hàng gần nhà để mua sắm. Bạn cũng có thể trực tiếp kiểm tra sản phẩm và nhận sự hỗ trợ từ nhân viên tại cửa hàng.• Dịch vụ hậu mãi chuyên nghiệp: Thế Giới Di Động cung cấp dịch vụ hậu mãi chuyên nghiệp, bao gồm bảo hành, sửa chữa và hỗ trợ kỹ thuật. Điều này giúp bạn yên tâm về việc sử dụng trong thời gian dài.• Trả góp linh hoạt: Thế Giới Di Động cung cấp các lựa chọn trả góp phù hợp với ngân sách của bạn, giúp bạn mua được sản phẩm mong muốn mà không cần thanh toán toàn bộ số tiền một lúc.• Uy tín và kinh nghiệm lâu năm: Với hơn 15 năm hoạt động trên thị trường, Thế Giới Di Động đã xây dựng được một uy tín mạnh mẽ trong ngành công nghiệp điện thoại di động. Điều này giúp bạn yên tâm về việc mua sắm tại Thế Giới Di Động.So sánh iPhone 15 Pro Max 256 GB và các sản phẩm iPhone 15 Series khác?Tiêu chíiPhone 15 Pro Max 256 GBiPhone 15 Pro 256 GBiPhone 15 Plus 256 GBiPhone 256 GBMàn hình\xa0 \xa0• Kích thước: 6.7 inch\xa0 \xa0• Super Retina XDR OLED\xa0 \xa0• Công nghệ ProMotion\xa0 \xa0• Dynamic Island\xa0 \xa0• 2796 x 1290 pixels\xa0 \xa0• Kích thước: 6.1 inch\xa0 \xa0• Super Retina XDR OLED\xa0 \xa0• Công nghệ ProMotion\xa0 \xa0• Dynamic Island\xa0 \xa0• 2556 x 1179 pixels\xa0 \xa0• Kích thước: 6.7 inch\xa0 \xa0• Super Retina XDR OLED\xa0 \xa0• Dynamic Island\xa0 \xa0• 2796 x 1290 pixels\xa0 \xa0• Kích thước: 6.1 inch\xa0 \xa0• Super Retina XDR OLED\xa0 \xa0• Dynamic Island\xa0 \xa0• 2556 x 1179 pixelsKích thước và khối lượng\xa0 \xa0• 159.9 mm x 76.7 mm x 8.25 mm\xa0 \xa0• 221 gram\xa0 \xa0• 146.6 mm x 70.6 mm x 8.25 mm\xa0 \xa0• 187g\xa0 \xa0• 160.9 mm x 77.8 mm x 7.8 mm\xa0 \xa0• 201 gram\xa0 \xa0• 147.6 mm x 71.6 mm x 7.8 mm\xa0 \xa0• 171 gramKhung viềnTitaniumTitaniumNhômNhômChipApple A17 ProApple A17 ProApple A16 BionicApple A16 BionicDung lượng\xa0 \xa0• 256GB\xa0 \xa0• 512GB\xa0 \xa0• 1TB\xa0 \xa0• 128GB\xa0 \xa0• 256GB\xa0 \xa0• 512GB\xa0 \xa0• 1TB\xa0 \xa0• 128GB\xa0 \xa0• 256GB\xa0 \xa0• 512GB\xa0 \xa0• 128GB\xa0 \xa0• 256GB\xa0 \xa0• 512GBCamera\xa0 \xa0• Camera trước: 12MP, f/1.9\xa0 \xa0• Camera chính: 48MP, f/1.78\xa0 \xa0• Camera góc siêu rộng: 12MP, f/2.2\xa0 \xa0• Camera Telephoto: 12MP, f/2.8, khả năng zoom 2x và 5x\xa0 \xa0• Camera trước: 12MP, f/1.9\xa0 \xa0• Camera chính: 48MP, f/1.78\xa0 \xa0• Camera góc siêu rộng: 12MP, f/2.2\xa0 \xa0• Camera Telephoto: 12MP, f/2.8, khả năng zoom 2x và 3x\xa0 \xa0• Camera trước: 12MP, f/1.9\xa0 \xa0• Camera chính: 48MP, f/1.6\xa0 \xa0• Camera góc siêu rộng: 12MP, f/2.4\xa0 \xa0• Camera trước: 12MP, f/1.9\xa0 \xa0• Camera chính: 48MP, f/1.6\xa0 \xa0• Camera góc siêu rộng: 12MP, f/2.4Nút tác vụCóCóKhôngKhôngThời lượng pin\xa0 \xa0• Nghe nhạc: 95 tiếng\xa0 \xa0• Xem video: 29 tiếng\xa0 \xa0• Xem video (trực tuyến): 25 tiếng\xa0 \xa0• Nghe nhạc: 75 tiếng\xa0 \xa0• Xem video: 23 tiếng\xa0 \xa0• Xem video (trực tuyến): 20 tiếng\xa0 \xa0• Nghe nhạc: 100 tiếng\xa0 \xa0• Xem video: 26 tiếng\xa0 \xa0• Xem video (trực tuyến): 20 tiếng\xa0 \xa0• Nghe nhạc: 80 tiếng\xa0 \xa0• Xem video: 20 tiếng\xa0 \xa0• Xem video (trực tuyến): 16 tiếngCảm biếnCảm biến tiệm cậnCảm biến tiệm cậnCảm biến tiệm cậnCảm biến tiệm cậnCổng kết nốiUSB-C hỗ trợ USB 3USB-C hỗ trợ USB 3USB-C hỗ trợ USB 2USB-C hỗ trợ USB 2So sánh iPhone 15 Pro Max 256 GB và iPhone 14 Pro Max 256 GB: Có đáng để nâng cấp?Dưới đây sẽ là bảng tổng hợp thông số kỹ thuật giữa hai thế hệ điện thoại iPhone:Tiêu chíiPhone 15 Pro Max 256 GBiPhone 14 Pro Max 256 GBMàn hình\xa0\xa0•\xa0Kích thước: 6.7 inch\xa0\xa0•\xa0Super Retina XDR OLED\xa0\xa0•\xa0Công nghệ ProMotion\xa0\xa0•\xa0Công nghệ True Tone\xa0\xa0•\xa0Dynamic Island\xa0\xa0•\xa02796 x 1290 pixels\xa0\xa0•\xa0Kích thước: 6.7 inch\xa0\xa0•\xa0Super Retina XDR OLED\xa0\xa0•\xa0Công nghệ True Tone\xa0\xa0•\xa0Công nghệ ProMotion\xa0\xa0•\xa0Dynamic Island\xa0\xa0•\xa02796 x 1290 pixelsKích thước và khối lượng\xa0\xa0•\xa0159.9 mm x 76.7 mm x 8.25 mm\xa0\xa0•\xa0221 gram\xa0\xa0•\xa0160.7 mm x 77.6 mm x 7.85 mm\xa0\xa0•\xa0240 gramKhung viềnTitaniumKim loại thép không gỉChipApple A17 ProApple A16 BionicRAM8 GB6 GBBộ nhớ trong256 GB, 512 GB, 1 TB128 GB, 256 GB, 512 GB, 1 TBCamera\xa0\xa0•\xa0Camera trước: 12MP, f/1.9\xa0\xa0•\xa0Camera chính: 48MP, f/1.78\xa0\xa0•\xa0Camera góc siêu rộng: 12MP, f/2.2\xa0\xa0•\xa0Camera Telephoto: 12MP, f/2.8, khả năng zoom 2x và 5x\xa0\xa0•\xa0Camera trước: 12MP\xa0\xa0•\xa0Camera chính: 48MP, f/1.78\xa0\xa0•\xa0Camera góc siêu rộng: 12MP, f/2.2\xa0\xa0•\xa0Camera Telephoto: 12MP, f/2.8 khả năng zoom 2x, 3xNút tác vụAction ButtonCần gạtDung lượng pin4422 mAh4323 mAhThời lượng pin\xa0\xa0•\xa0Nghe nhạc: 95 tiếng\xa0\xa0•\xa0Xem video: 29 tiếng\xa0\xa0•\xa0Xem video (trực tuyến): 25 tiếng\xa0\xa0•\xa0Nghe nhạc: 95 tiếng\xa0\xa0•\xa0Xem video: 29 tiếng\xa0\xa0•\xa0Xem video (trực tuyến): 25 tiếngCảm biến\xa0\xa0•\xa0LiDAR Scanner\xa0\xa0•\xa0Face ID\xa0\xa0•\xa0Con quay hồi chuyển độ lệch tương phản cao\xa0\xa0•\xa0Gia tốc kế lực G cao\xa0\xa0•\xa0Cảm biến tiệm cận\xa0\xa0•\xa0Hai cảm biến ánh sáng môi trường\xa0\xa0•\xa0Áp kế\xa0\xa0•\xa0LiDAR Scanner\xa0\xa0•\xa0Face ID\xa0\xa0•\xa0Con quay hồi chuyển độ lệch tương phản cao\xa0\xa0•\xa0Gia tốc kế lực G cao\xa0\xa0•\xa0Cảm biến tiệm cận\xa0\xa0•\xa0Hai cảm biến ánh sáng môi trường\xa0\xa0•\xa0Áp kếCổng kết nốiUSB-C hỗ trợ USB 3Lightning hỗ trợ USB 2Công suất sạc20 W20 WThời gian sạcSạc tới 50% trong 35 phútSạc tới 50% trong 35 phútMàu sắcTitan tự nhiên (Natural Titanium), Titan trắng (White Titanium), Titan đen (Black Titanium), Titan xanh (Blue Titanium)Vàng, Đen, Bạc, TímKết nốiWi‑Fi 6E, 5GWi‑Fi 6, 5GVideo giới thiệu điện thoại iPhone 15 Pro và iPhone 15 Pro MaxiPhone 15 Pro Max mẫu điện thoại mới nhất của Apple cuối cùng cũng đã chính thức được ra mắt vào tháng 09/2023. Mẫu điện thoại này sở hữu một con chip với hiệu năng mạnh mẽ Apple A17 Pro, màn hình đẹp mắt và cụm camera vô cùng chất lượng.Diện mạo đẳng cấp và cực kỳ sang trọngiPhone 15 Pro Max tiếp tục sẽ là một chiếc điện thoại có màn hình và mặt lưng phẳng đặc trưng đến từ nhà Apple, mang lại vẻ đẹp thanh lịch và sang trọng.Chất liệu chủ đạo của iPhone 15 Pro Max vẫn là khung kim loại và mặt lưng kính cường lực, tạo nên sự bền bỉ và chắc chắn. Tuy nhiên, với công nghệ tiên tiến, khung này đã được nâng cấp thành chất liệu titanium thay vì thép không gỉ hay nhôm ở những thế hệ trước.Nguồn: Ảnh được trích từ Apple.comNăm nay có một chút thay đổi về phần thiết kế bộ khung nhờ cách tạo viền mới, phần viền giờ đây đã ít phẳng đi một chút để tạo sự bo cong nhẹ giúp mang lại cảm giác cầm nắm tuyệt vời hơn, sử dụng điện thoại trong thời gian dài vì thế cũng trở nên dễ chịu.Nguồn: Ảnh được trích từ Apple.comThiết kế hình notch dạng viên thuốc tiếp tục xuất hiện trên iPhone 15 Pro Max, giúp mang đến trải nghiệm sử dụng thú vị hơn bao giờ hết và đặc biệt hơn khi đi kèm với tính năng Dynamic Island.Nguồn: Ảnh được trích từ Apple.comTrang bị kiểu hình notch dạng Dynamic IslandDynamic Island là một tính năng độc đáo mà iPhone 15 Pro Max mang đến. Đây là một phần của màn hình dành riêng cho thông báo và tương tác nhanh chóng mà không làm gián đoạn trải nghiệm xem nội dung chính. Dynamic Island giúp bạn dễ dàng kiểm tra thông báo, kiểm soát âm nhạc, và thậm chí là xem bản đồ mà không cần thoát khỏi ứng dụng bạn đang sử dụng.Nguồn: Ảnh được trích từ Apple.comKhi có hai hoạt động xảy ra đồng thời, Dynamic Island sẽ tách thành hai phần. Do đó, bạn hiện có thể trò chuyện với bạn bè và đồng thời xem thời gian trôi qua. Hoặc bạn có thể theo dõi điểm số của đội trong khi đánh giá tốc độ của chạy cá nhân. Chỉ cần chạm và giữ để mở rộng một trong những hoạt động này hoặc nhấn để khởi chạy ứng dụng.Tính năng bong bóng nhân đôi hoạt động dựa trên Dynamic Island : Ảnh trích từ InternetSử dụng cổng kết nối mớiMột sự thay đổi lớn khác nằm ở cổng kết nối, iPhone 15 Pro Max đã chuyển từ cổng Lightning sang Type-C, mang lại tốc độ truyền dữ liệu nhanh hơn và tích hợp cơ động hơn với nhiều thiết bị khác.Giờ đây người dùng có thể dùng chung cáp sạc của iPhone 15 Pro Max cho cả Mac, iPad, Apple Watch, AirPods* giúp mang đến một sự tiện lợi trong việc sử dụng phụ kiện, từ đó tối ưu được không gian của bạn bởi không bị ảnh hưởng do có quá nhiều dây sạc.*Áp dụng đối với những phiên bản thế hệ mới có hỗ trợ chuẩn Type CNguồn: Ảnh được trích từ Apple.comTrang bị công nghệ eSIMiPhone 15 Pro Max được hỗ trợ sử dụng eSIM, trong đó điện thoại có khả năng lưu trữ hơn 8 eSIM và có thể kích hoạt chúng bất cứ khi nào bạn cần. Tuy nhiên, tùy vào từng thị trường ở mỗi khu vực mà máy chỉ hỗ trợ sử dụng được 1 hoặc 2 trong số 8 eSIM mà bạn lưu trữ.eSIM có thể được kích hoạt trực tuyến, giúp người dùng dễ dàng chuyển đổi giữa các nhà mạng hoặc sử dụng nhiều số điện thoại trên cùng một chiếc iPhone. Người dùng chỉ cần truy cập trang web hoặc ứng dụng của nhà mạng để kích hoạt eSIM, không cần phải đến cửa hàng của nhà mạng để làm thủ tục.Thay đổi cơ chế hoạt động nút tác vụTrong sự thay đổi này, Apple đã biến phím gạt chế độ im lặng truyền thống thành một nút bấm nhỏ gọn, tạo thuận tiện trong việc thay đổi chế độ âm thanh và tắt tiếng trong môi trường yên tĩnh.Nguồn: Ảnh được trích từ InternetLưu giữ trọn vẹn mọi khoảnh khắc với camera 48 MPNâng cấp đáng chú ý nhất trên camera iPhone 15 Pro Max là cảm biến chính 48 MP, nó cho phép thu được nhiều ánh sáng hơn và chụp ảnh, quay video trong điều kiện thiếu sáng tốt hơn. Ngoài ra, cảm biến 48 MP cũng giúp cho iPhone 15 Pro Max quay video 4K nhằm cho ra những thước phim chuẩn điện ảnh.Nguồn: Ảnh được trích từ Apple.comChế độ Smart HDR 5 mới trên iPhone 15 Pro Max sử dụng AI để tối ưu hóa độ sáng, màu sắc và độ tương phản của ảnh. Chế độ này giúp ảnh chụp trên iPhone 15 Pro Max luôn sáng rõ, màu sắc sống động và chi tiết.Nguồn: Ảnh được trích từ Apple.comChế độ Cinematic trên iPhone 15 Pro Max cho phép người dùng quay video với hiệu ứng xóa phông tự nhiên. Hơn hết, chế độ còn có khả năng tự động lấy nét vào đối tượng chính và làm mờ hậu cảnh, từ đó giúp video trông chuyên nghiệp hơn khi chủ thể hay nhân vật quan trọng trong đám đông được làm nổi bật.Nguồn: Ảnh được trích từ Apple.comĐể đảm bảo video và ảnh của bạn luôn ổn định và không bị rung, iPhone 15 Pro Max được trang bị tính năng chống rung tối đa trong đó có kể kể đến Action Mode (chế độ hành động). Ngay cả khi bạn quay video trong điều kiện chuyển động, kết quả vẫn sẽ thật ấn tượng và chuyên nghiệp.Nguồn: Ảnh được trích từ Apple.comCamera trước 12 MP, cho phép chụp ảnh selfie sắc nét hơn. Ngoài ra, camera trước cũng hỗ trợ quay video 4K, giúp người dùng quay lại những khoảnh khắc đáng nhớ một cách rõ ràng và sống động.Trải nghiệm chụp ảnh chuẩn chuyên gia thông qua chế độ chụp chân dungTrong chế độ chân dung, giờ đây người dùng được phép thực hiện việc thu phóng một cách liền mạch và chính xác. Bạn có thể tận hưởng việc di chuyển từng bước một và tiến sâu vào chi tiết của chủ thể mà bạn đang chụp, giúp mang đến sự linh hoạt và khả năng tạo ra các bức tranh chân dung một cách tự nhiên.Nguồn: Ảnh được trích từ Apple.comĐiều thú vị hơn nữa là khả năng chuyển đổi tiêu điểm giữa các đối tượng sau khi bạn đã thực hiện chụp. Bạn không cần phải quay lại sau khi chụp để chỉnh sửa tiêu điểm. Thay vào đó, bạn có thể dễ dàng điều chỉnh tiêu điểm từng đối tượng ngay trên màn hình cảm ứng của bạn. Điều này cho phép bạn thực hiện các thay đổi nhanh chóng và tạo ra những bức ảnh động và sáng tạo.Nguồn: Ảnh được trích từ Apple.comCông cụ Photonic giờ đây cũng đã được trang bị trong chế độ chụp ảnh chân dung, Photonic Tool mang lại một loạt cải tiến đáng kể cho chức năng chụp ảnh chân dung trên iPhone 15 Pro Max. Bạn sẽ trải nghiệm sự cải thiện vượt trội về chi tiết, sắc thái màu sắc tự nhiên, hạn chế độ trễ màn trập xuống tối thiểu và hiệu suất chụp ảnh trong điều kiện ánh sáng yếu được cải thiện gấp đôi.Nâng cao trải nghiệm hình ảnh với màn hình chân thựcMàn hình của iPhone 15 Pro Max sử dụng tấm nền OLED, đây là công nghệ hiển thị đỉnh cao giúp tạo ra độ sâu màu sắc tuyệt vời và độ tương phản cực cao. Màu đen được tái hiện một cách có chiều sâu, giúp tạo ra trải nghiệm xem ảnh và video chân thực và sống động hơn bao giờ hết.Xem thêm: Màn hình OLED là gì? Có gì nổi bật? Thiết bị nào có màn hình OLED?Độ phân giải lên đến 1290 x 2796 Pixels trên màn hình 6.7 inch giúp bạn thấy rõ từng chi tiết, từ văn bản tới hình ảnh chất lượng cao. Điều này đồng nghĩa với việc bạn có thể thưởng thức nội dung đa phương tiện với độ sắc nét và chi tiết vượt trội.Ngoài ra, iPhone 15 Pro Max được trang bị viền màn hình mỏng hơn so với iPhone 14 Pro Max. Điều này mang lại trải nghiệm xem vô cùng thoải mái, như thể bạn đang đắm chìm trong thế giới của màn hình. Viền màn hình mỏng cũng giúp tổng thể thiết kế của máy trở nên thanh thoát và tinh tế hơn, khiến iPhone 15 Pro Max trở thành một trong những chiếc điện thoại đẹp nhất trên thị trường hiện nay.Màn hình của iPhone 15 Pro Max được trang bị mặt kính cường lực chất lượng cao, giúp bảo vệ màn hình khỏi vết trầy xước và va đập. Điều này đồng nghĩa với việc bạn có thể sử dụng điện thoại mà không cần lo lắng về việc bảo vệ màn hình.Nguồn: Ảnh được trích từ Apple.comMàn hình của iPhone 15 Pro Max hỗ trợ tần số quét lên tới 120 Hz, mang lại trải nghiệm trượt và cuộn mượt mà hơn bao giờ hết. Độ sáng lên đến 2000 nits giúp màn hình sáng rực, thậm chí ở ngoài trời nắng gắt, bạn vẫn có thể thấy mọi chi tiết một cách rõ ràng.Ngoài các tính năng đã đề cập ở trên, màn hình iPhone 15 Pro Max còn được trang bị một số công nghệ phụ khác, giúp nâng cao trải nghiệm giải trí của người dùng như True Tone tự động điều chỉnh màu sắc và độ sáng màn hình dựa trên môi trường xung quanh giúp người dùng có được trải nghiệm xem thoải mái hơn.Ngoài ra máy còn có công nghệ ProMotion, nó cho phép màn hình iPhone 15 Pro Max thay đổi tốc độ quét theo nội dung đang hiển thị, giúp tiết kiệm pin và mang lại trải nghiệm mượt mà hơn.Cấu hình cực khủng trên thị trườngSức mạnh của iPhone 15 Pro Max bắt đầu từ vi xử lý Apple A17 Pro, một con chip mạnh mẽ được thiết kế riêng cho Apple. Với sự cải tiến vượt bậc trong khả năng xử lý đa nhiệm và đồ họa, chiếc điện thoại này sẽ đảm bảo bạn có trải nghiệm mượt mà và nhanh chóng khi sử dụng mọi ứng dụng và trò chơi yêu thích.Chiếc điện thoại chơi game cấu hình cao này sẽ được trang bị RAM lớn, cho phép bạn chạy đa nhiệm mà không gặp trở ngại. Từ việc duyệt web, xem video, đến chơi game nặng, bạn có thể tự tin thực hiện mọi thứ một cách mượt mà và nhanh chóng.Nguồn: Ảnh được trích từ Apple.comHỗ trợ hệ điều hành iOS mới nhất 2023iPhone 15 Pro Max chạy trên hệ điều hành iOS 17, phiên bản mới nhất của Apple. iOS 17 mang đến những cải tiến đáng kể về hiệu năng, bảo mật và trải nghiệm người dùng. Bạn sẽ được trải nghiệm những tính năng mới thú vị và giao diện người dùng mượt mà hơn bao giờ hết.Xem thêm: iOS 17 chính thức: Khi nào ra mắt, có gì mới, hỗ trợ máy nào?Nguồn: Ảnh được trích từ Apple.comÁp phích liên hệÁp phích liên hệ trên iOS 17 là một tính năng mới trên iOS 17, nó cho phép bạn tạo ảnh đại diện tùy chỉnh cho các liên hệ của mình. Áp phích liên hệ có thể bao gồm ảnh, văn bản và các yếu tố đồ họa khác. Bạn có thể sử dụng áp phích liên hệ để làm cho danh bạ của mình trông đẹp hơn và dễ nhận biết hơn.NameDropNameDrop là một tính năng mới được giới thiệu trong bản cập nhật iOS 17 của Apple. Tính năng này giúp người dùng chia sẻ thông tin liên hệ, chẳng hạn như số điện thoại, địa chỉ email, và ảnh hồ sơ, giữa các thiết bị Apple chỉ bằng cách chạm hai thiết bị vào nhau.Để sử dụng NameDrop, người dùng cần bật AirDrop trên cả hai thiết bị. Sau đó, chỉ cần chạm hai thiết bị vào nhau và giữ trong vài giây. Nếu cả hai thiết bị đều hỗ trợ NameDrop, một cửa sổ sẽ bật lên trên màn hình của thiết bị nhận. Người dùng có thể chọn chia sẻ thông tin liên hệ của mình với thiết bị kia.Nhãn dán độngNhãn dán động trên iOS 17 là một loại nhãn dán mới có thể được tạo từ ảnh, video hoặc Live Photo. Các nhãn dán này có thể được sử dụng trong ứng dụng Tin nhắn, ứng dụng Ghi chú và ứng dụng Đánh dấu.Để tạo nhãn dán động, người dùng có thể sử dụng công cụ cắt và chỉnh sửa ảnh hoặc video trong ứng dụng Tin nhắn. Sau khi tạo xong, nhãn dán động sẽ được lưu vào ngăn nhãn dán mới trong bàn phím biểu tượng.Nhãn dán động có thể được sử dụng để làm cho cuộc trò chuyện trở nên sinh động và thú vị hơn. Người dùng có thể sử dụng nhãn dán động để biểu đạt cảm xúc, chia sẻ suy nghĩ hoặc kể một câu chuyện.Thời gian sử dụng cực lâu cùng khả năng sạc nhanhMột trong những điểm đáng chú ý nhất của iPhone 15 Pro Max là viên pin có thời lượng dùng dài lâu với 4422 mAh, việc này đảm bảo bạn có thể sử dụng chiếc\xa0iPhone này một cách thoải mái suốt cả ngày mà không cần phải lo lắng về việc sạc lại. Nổi bật hơn hết, Apple cho biết iPhone 15 Pro Max có thời lượng phát video nhiều hơn tới 9 giờ so với iPhone 12 Pro Max (3687 mAh), quả là một sự chênh lệch khủng.Với viên pin lớn như vậy, iPhone 15 Pro Max có đủ năng lượng để cung cấp cho bạn 29 giờ phát lại video liên tục mà không cần cắm sạc, điều này giúp trải nghiệm của bạn trở nên liền mạch hơn và ít có sự gián đoạn gây khó chịu.iPhone 15 Pro Max được trang bị khả năng sạc nhanh lên đến 20 W, giúp bạn nạp năng lượng nhanh chóng. Điều này đồng nghĩa với việc bạn có thể sạc lại pin từ 0% lên đến hơn 50% trong thời gian ngắn, giúp tiết kiệm thời gian đáng kể. Khả năng sạc nhanh còn rất hữu ích khi bạn cần sử dụng điện thoại ngay lập tức sau một thời gian ngắn sạc pin.Nguồn: Ảnh được trích từ Apple.comiOS 17, hệ điều hành mới nhất của Apple cũng mang đến những cải tiến về quản lý pin. Bạn có thể kiểm soát ứng dụng tiêu thụ nhiều năng lượng và tối ưu hóa cài đặt để kéo dài thời gian sử dụng pin của iPhone 15 Pro Max.Các tính năng - tiện ích trên iPhone 15 Pro MaxHỗ trợ bên đường qua vệ tinhHỗ trợ bên đường qua vệ tinh là tính năng mới được Apple giới thiệu trên iPhone 15 Pro Max. Tính năng này cho phép người dùng gửi yêu cầu hỗ trợ bên đường đến nhà cung cấp dịch vụ hỗ trợ bên đường khi gặp sự cố trên đường. Yêu cầu hỗ trợ sẽ được gửi qua vệ tinh, ngay cả khi iPhone của bạn không có kết nối mạng di động hoặc Wi-Fi.Nguồn: Ảnh được trích từ Apple.comTính năng phát hiện va chạm Tính năng phát hiện va chạm trên iPhone 15 Pro Max là một tính năng an toàn được Apple giới thiệu. Tính năng này sử dụng các cảm biến trên iPhone để phát hiện các vụ va chạm ô tô nghiêm trọng. Khi phát hiện ra va chạm, iPhone sẽ tự động gọi điện thoại đến dịch vụ khẩn cấp hoặc các số liên hệ khẩn cấp mà bạn đã đặt trước.Kết hợp với hệ sinh thái AppleiPhone và Apple WatchiPhone và Apple Watch là hai sản phẩm được sử dụng phổ biến nhất của Apple. Hai sản phẩm này được thiết kế để hoạt động cùng nhau một cách liền mạch.Người dùng có thể sử dụng Apple Watch để trả lời cuộc gọi, kiểm tra tin nhắn, và điều khiển các ứng dụng trên iPhone. Apple Watch

In [120]:
# B3: Back lại trang trước:
driver.back()

In [121]:
driver.current_url

'https://www.thegioididong.com/dtdd/iphone-15-pro-max'

#### Create function to get product description

In [45]:
from time import sleep

In [79]:
def get_product_description(product_elm):
    # B1: Click vao product:
    product_elm.click()

    sleep(2)

    # B2: get production description:
    try:
        product_description = driver.find_element(By.CLASS_NAME, 'content-article').get_attribute('textContent')
    except:
        product_description = driver.find_element(By.CLASS_NAME, 'article__content').get_attribute('textContent')

    # B3: Back lại trang trước:
    driver.back()
    sleep(2)

    return product_description

In [63]:
get_product_description(product_elm=product_list[5])

'\n                    Trong khi sức hút đến từ bộ 4 phiên bản\xa0iPhone 12\xa0vẫn chưa nguội đi, thì hãng điện thoại\xa0Apple\xa0đã mang đến cho người dùng một siêu phẩm mới iPhone 13 series với\xa0nhiều cải tiến thú vị sẽ mang lại những trải nghiệm hấp dẫn nhất cho người dùng.Hiệu năng vượt trội nhờ chip Apple A15 BionicCon chip Apple A15 Bionic\xa0siêu mạnh được sản xuất trên quy trình 5 nm giúp iPhone 13\xa0đạt hiệu năng ấn tượng, với CPU nhanh hơn 50%,\xa0GPU nhanh hơn 30% so với các đối thủ trong cùng phân khúc.Nhờ hiệu năng được cải tiến, người dùng có được những trải nghiệm tốt hơn trên điện thoại khi dùng các ứng dụng chỉnh sửa ảnh hay chiến các tựa game đồ họa cao mượt mà.iPhone 13 trang bị\xa0bộ nhớ trong 128 GB\xa0dung lượng lý tưởng\xa0cho phép bạn thỏa thích lưu trữ mọi nội dung theo ý muốn mà không lo nhanh đầy bộ nhớ.Tốc độ 5G tốt hơn\xa0Mạng 5G được cải thiện chất lượng với nhiều băng tần hơn, với 5G giúp điện thoại xem trực tuyến hay tải xuống các ứng dụng và tài liệu đều đạt tốc độ nhanh chóng. Không chỉ vậy, siêu phẩm mới này còn có chế độ dữ liệu thông minh, tự động phát hiện và giảm tải tốc độ mạng để tiết kiệm năng lượng khi không cần dùng tốc độ cao.Màn hình Super Retina XDR độ sáng cao, tiết kiệm piniPhone 13 sử dụng tấm nền OLED với kích thước màn hình 6.1 inch\xa0cho chất lượng màu sắc và chi tiết hình ảnh sắc nét, sống động, độ phân giải đạt 1170 x 2532 Pixels.Nhờ có công nghệ Super Retina XDR giúp cho máy đạt\xa0độ sáng 800 nits, tối đa lên đến 1200 nits cùng dải màu rộng P3, tỷ lệ tương phản lớn giúp ổn định tốt màu sắc và chất lượng hình ảnh hiển thị trong nhiều điều kiện sáng khác nhau, kể cả môi trường nắng gắt hay ánh sáng chói.Phía ngoài màn hình còn được phủ lớp oleophobic hạn chế tình trạng bám bụi bẩn và mồ hôi do tay người dùng, giữ màn hình luôn sạch và tinh tế hơn. Và trang bị\xa0kính cường lực Ceramic Shield giúp màn hình của máy được an toàn hơn trước những vết xước, va đập trong quá trình sử dụng.Cụm camera kép nổi bật với nhiều cải tiếnCụm camera kép phía sau trên iPhone 13 đều sở hữu độ phân giải 12 MP, camera chính\xa0giúp thu được nhiều ánh sáng hơn, tăng khả năng thu sáng lên đến 47% nên chất lượng ảnh chụp cũng cải thiện hơn so với bản tiền nhiệm. Điện thoại có\xa0camera góc siêu rộng\xa0cho góc nhìn\xa0120 độ giúp thu được nhiều chi tiết hơn, dễ dàng ghi lại những khung cảnh núi non hùng vĩ, ảnh chụp nhóm đông người.Cụm camera cũng được trang bị tính năng chống rung quang học Sensor Shift giúp lấy nét nhanh chóng, khả năng chụp đêm cũng trở nên rõ nét mà ít bị nhiễu hạt, hay quay video cũng rất ổn định và mượt mà hơn.“Chế độ điện ảnh” cho phép camera trên iPhone 13 tự động làm mờ hậu cảnh trong video để đối tượng luôn được lấy nét nổi bật. Đặc biệt người dùng có thể thay đổi tiêu điểm để chọn chủ thể mong muốn trong khung hình khi sử dụng quay video, nhờ đó tạo nên những video chuyên nghiệp, như ý hơn.Chế độ chụp Smart HDR 4 nhận diện tối đa 4 người trong một khung hình, tiến hành tối ưu hóa ánh sáng và tương phản, tone màu da cho từng người để hoàn thiện bức ảnh đẹp mà không cần qua chỉnh sửa.Camera trước vẫn nằm trong tai thỏ, độ phân giải cũng đạt 12 MP với các công nghệ chụp ảnh chuyên nghiệp như hiệu ứng bokeh, chế độ điện ảnh, Animoji và Memoji để bạn tự tin thể hiện mình trước ống kính, không lo lắng che giấu khuyết điểm.Sang trọng, đẳng cấp hơn về ngoại hìnhiPhone 13\xa0có thiết kế nguyên khối vuông vắn như tiền nhiệm, khung viền được làm từ nhôm cùng mặt lưng kính sang trọng, cao cấp.Ngoại hình không quá khác biệt so với tiền nhiệm, nhưng tỷ lệ màn hình so với khung máy tốt hơn, phần tai thỏ nhỏ hơn 20% gia tăng diện tích trải nghiệm khi lướt web, xem phim, chơi game.Điểm khác biệt lớn nhất trong ngoại hình có lẽ chính là các cảm biến camera được đặt chéo thay vì xếp thẳng hàng như iPhone 12, tạo điểm nhận diện đặc trưng, mới mẻ và đẹp mắt, sang chảnh hơn.Màu sắc trên mẫu iPhone mới này cũng đa dạng hơn gồm Trắng, Đen, Đỏ, Xanh dương và Hồng mới mẻ dễ tùy chọn cho mọi người dùng.iPhone 13 hỗ trợ chuẩn kháng nước và bụi IP68, bạn sẽ yên tâm sử dụng hơn khi đem theo thiết bị để chụp ảnh khi bơi hay những lần vô tình làm đổ nước, có cơn mưa đột ngột.Thời lượng pin cũng được cải thiệnTheo công bố của hãng, iPhone 13 có thời lượng pin tăng thêm 2.5 tiếng so với thế hệ trước, cho thời gian sử dụng lâu hơn, phục vụ hiệu quả với người dùng có nhu cầu sử dụng tần suất cao.Hỗ trợ\xa0sạc nhanh\xa020 W giúp nạp đầy 50% pin chỉ trong khoảng 30 phút. Đi kèm theo các công nghệ sạc không dây\xa0tiên tiến như chuẩn Qi hay MagSafe.Lưu ý: Củ sạc nhanh 20 W sẽ không đi kèm trong hộp khi mua.Tóm lại, với những nâng cấp và cải tiến mạnh mẽ về hiệu năng, camera đa chức năng, mình nghĩ rằng iPhone 13 128GB sẽ là một chiếc điện thoại cao cấp rất đáng được đầu tư và sử dụng.Tham khảo ngay loạt sản phẩm iPhone mới nhất năm 2022 nhiều mẫu mã: iPhone 14, iPhone 14 Pro, iPhone 14 Plus, iPhone 14 Pro Max khuyến mãi giảm giá đến hàng triệu kèm nhiều quà tặng kèm theo hấp dẫn đang chờ bạn.\n                '

In [ ]:
listproduct_elm = driver.find_element(By.CLASS_NAME, 'listproduct')
product_list = listproduct_elm.find_elements(By.CLASS_NAME, 'item')

In [75]:
product_list_url = driver.current_url
product_list_url

'https://www.thegioididong.com/dtdd#c=42&m=2,80,2235&o=17&pi=4'

In [82]:
len(product_list)

84

In [83]:

all_product_list = []
for i in range(len(product_list)):
    for t in range(10):
        try:
            prd_elm = product_list[i]
            product_info = get_product_info(prd_elm)
            product_info['description'] = get_product_description(prd_elm)
            all_product_list.append(product_info)
            break
        except:
            driver.get(product_list_url)
            sleep(2)
            listproduct_elm = driver.find_element(By.CLASS_NAME, 'listproduct')
            product_list = listproduct_elm.find_elements(By.CLASS_NAME, 'item')

In [86]:
desc_df = pd.DataFrame( all_product_list)
desc_df.head()

,name,price,utility,img_link,description
0,iPhone 15 Pro Max 256GB,29.590.000₫,Chip Apple A17 Pro 6 nhân\nRAM: 8 GB\nDung lượ...,https://cdn.tgdd.vn/Products/Images/42/305658/...,\n Đặc điểm nổi bật của iPh...
1,iPhone 13 256GB,16.990.000₫,Chip Apple A15 Bionic\nRAM: 4 GB\nDung lượng: ...,None,\n Apple thỏa mãn sự chờ đó...
2,Samsung Galaxy S23 Ultra 5G 256GB,24.990.000₫,Chip Snapdragon 8 Gen 2 for Galaxy\nRAM: 8 GB\...,https://cdn.tgdd.vn/Products/Images/42/249948/...,\n Samsung Galaxy S23 Ultra...
3,Xiaomi Redmi Note 13 (8GB/128GB),4.390.000₫,Chip Snapdragon 685 8 nhân\nRAM: 8 GB\nDung lư...,https://cdn.tgdd.vn/Products/Images/42/309831/...,"\n Vào tháng 01/2024, Xiaom..."
4,Samsung Galaxy A55 5G (8GB/256GB),10.190.000₫,Chip Exynos 1480 8 nhân\nRAM: 8 GB\nDung lượng...,https://cdn.tgdd.vn/Products/Images/42/322670/...,\n Bài viết đánh giá\n ...

In [88]:
df = pd.merge(
    left = df,
    right = desc_df[['name', 'description']],
    how = 'left',
    on = 'name'
)

In [91]:
df.to_excel(r'C:\Users\Windows\Desktop\Crawl data from website\data\phone_data.xlsx', index=False)